apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocs-operator
  namespace: openshift-storage
spec:
  selector:
    matchLabels:
      name: ocs-operator
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: ocs-operator
    spec:
      serviceAccountName: ocs-operator
      containers:
      - command:
        - ocs-operator
        args:
        - --enable-leader-election
        - "--health-probe-bind-address=:8081"
        image: ocs-dev/ocs-operator:latest
        imagePullPolicy: Always
        name: ocs-operator
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
              drop:
                - all
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
