apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  namespace: openshift-storage
  name: example-storagecluster
spec:
  manageNodes: false
  monPVCTemplate:
    spec:
      storageClassName: gp2-csi
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  storageDeviceSets:
  - name: example-deviceset
    count: 3
    resources: {}
    placement: {}
    dataPVCTemplate:
      spec:
        storageClassName: gp2-csi
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: 1Ti
    portable: true